language: php

php:
    - 7.3

install:
    - composer install

script:
    # before to see output
    - bin/run

    # compile to dummy.phar
    - bin/build.sh

    # this should be same as "bin/run" and work without local vendor
    - rm -rf /vendor
    - ./dummy.phar
