language: php

php:
    - 7.3

install:
    - composer update

script:
    - bin/run # before to see output

    # phar
    - bin/build.sh # compile to dummy.phar
    - ./dummy.phar # this file should exist and work
