language: php

php:
    - 7.3

install:
    - composer update

script:
    - bin/run # before compile

    # phar
    - bin/build.sh # compile to dummy.phar
    - tmp/build/dummy.phar # this file should exist and be runable
